version: "3.9"

services:
  front:
    depends_on:
      - api
    image: sermalenk/skypro-front:base
    ports:
      - 8080:80
    networks:
      - main

  api:
    image: 'husia777/todo:1'
    ports:
      - 8000:8000
    expose:
      - 8000
    depends_on:
      - migrations
      - postgres
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000

    volumes:
      - ./:/usr/src/app 
    networks:
      - main

  migrations:
    image: 'husia777/todo:1'
    depends_on:
      - postgres
    volumes:
      - ./backend/core/migrations:/usr/src/app/backend/core/migrations
    command: >
      sh -c "python manage.py makemigrations &&
            python manage.py makemigrations core &&
             python manage.py migrate"
    networks:
      - main
  postgres:
    image: postgres:14.6-alpine
    ports:
      - 5433:5432

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    networks:
      - main
  web:
    image: nginx
    volumes:
    - ./templates:/etc/nginx/templates
    ports:
    - "8080:80"
    environment:
    - NGINX_HOST=foobar.com
    - NGINX_PORT=80
  networks:
      - main
volumes:
  postgres_data:
  frontend:
  
networks:
  main: