version: "3.9"

services:
  nginx:
    build: ./nginx
    ports:
      - 1377:80
    depends_on:
      - api
  front:
    depends_on:
      - api
    image: sermalenk/skypro-front:base
    ports:
      - "8080:80"

  api:
    build: .
    depends_on:
      - postgres
    command: alembic upgrade head &&  uvicorn main:app --host 127.0.0.1:8000
    ports:
      - 3000:3000
    env_file:
      - .env
    volumes:
      - ./:/usr/src/app
      - ./backend/core/migrations:/usr/src/app/backend/core/migrations
  postgres:
    image: postgres:14.6-alpine
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    ports:
      - "5433:5432"

volumes:
  postgres_data:
