version: "3.9"

services:
  front:
    depends_on:
      - api
    image: sermalenk/skypro-front:base
    ports:
      - 80:80
    networks:
      - front
  api:
    build:
      context: .
    depends_on:
      - migrations
      - postgres
    volumes:
      - ./:/usr/src/app
    restart: always
    networks:
      - front
      - db

  migrations:
    build:
      context:
        .
    depends_on:
      - postgres
    volumes:
      - ./backend/core/migrations:/usr/src/app/backend/core/migrations
    command: >
      sh -c "python manage.py makemigrations &&
            python manage.py makemigrations core &&
             python manage.py migrate"
    networks:
      - db
  postgres:
    image: postgres:14.6-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    networks:
      - db

    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

volumes:
    postgres_data:
networks:
  front:
  db: