version: "3.9"

services:
  front:
    depends_on:
      - api
    image: sermalenk/skypro-front:base
    ports:
      - "80:80"

  api:
    build: .
    depends_on:
      - postgres
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./:/usr/src/app

  migrations:
    build: .
    depends_on:
      - postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432

    volumes:
      - ./backend/core/migrations:/usr/src/app/backend/core/migrations
    command: >
      sh -c "python manage.py migrate --noinput"
  postgres:
    image: postgres:14.6-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - "POSTGRES_HOST_AUTH_METHOD=trust"

    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    ports:
      - "5433:5432"

volumes:
  postgres_data:
