"""Database creati123

Revision ID: a2ba68a3bec5
Revises: 53620f730443
Create Date: 2023-04-13 16:30:43.007502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2ba68a3bec5'
down_revision = '53620f730443'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
